### ISSUE TITLE
cant use yolov7.pt

### ISSUE THREAD

**Issue by bedoman5** [theos-ai/easy-yolov7#1]
when i change 
yolov7.load('coco.weights', classes='coco.yaml', device='gpu') # use 'gpu' for CUDA GPU inference
to this below it doesnt work it just shows video without boxes
yolov7.load('yolov7.pt', classes='coco.yaml', device='gpu') # use 'gpu' for CUDA GPU inference
any answers pls

**Comment by ramacastro** [comment]
Hi 👋🏻 

Did you train the model with https://theos.ai ? 

This was tested using the weights downloaded from training experiments within Theos.

**Comment by bedoman5** [comment]
> Hi 👋🏻
> 
> Did you train the model with https://theos.ai ?
> 
> This was tested using the weights downloaded from training experiments within Theos.

hey , no i am using the official yolov7.pt model from git

**Comment by ramacastro** [comment]
You can import the dataset with labels to Theos and train it again.

Here are all the dataset formats we support currently: https://docs.theos.ai/datasets/image/labels/bounding-box/formats

If you have another format let us know so we can add it!

Also, if you have more than 1k images let us know and we can upgrade your plan for free.
