### ISSUE TITLE
not possible to install on jetson nano

### ISSUE THREAD

**Issue by mow** [theos-ai/easy-yolov7#4]
hello everyone & thanks for this. 

unfortunately it's not possible to install easy-yolov7 on a jetson nano with jetpack 4.6.1, either with python 37 or 38, since some multiple dependencies fails on 37 and paddlepaddle 2.4.2 on 3.8

`INFO: pip is looking at multiple versions of easy-paddle-ocr to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement paddlepaddle==2.4.2 (from easy-paddle-ocr) (from versions: none)
ERROR: No matching distribution found for paddlepaddle==2.4.2`

seems that there is no paddlepaddle 2.4.2 for aarch64 (?)

**Comment by g-a-pet** [comment]
It is possible and you will find paddlepaddle compiled with gpu on nvidia dev forums (use the py3.6 version since you already have preinstalled opencv, numpy etc. preinstalled. 
While this is an awesome repo, i would not recommend it for jetson nano. 
You will get a huge boost in performance if you use tensorrt to do inference on the jetson nano. 
I would recommend looking into the tensorrtx repo for converting your custom model into trt engine. Also use yolov7-tiny to further boost performance.

**Comment by mow** [comment]
wow thanks for this fast response :) I already tried to install appropriate paddlepaddle_gpu from https://forums.developer.nvidia.com/t/paddlepaddle-for-jetson/242765, it also fails :( 

now after you suggest 3.6 I tried with it and the result is;

`ERROR: Could not find a version that satisfies the requirement cachetools==5.2.0 (from versions: 0.0.0, 0.1.0, 0.2.0, 0.3.0, 0.3.1, 0.4.0, 0.5.0, 0.5.1, 0.6.0, 0.7.0, 0.7.1, 0.8.0, 0.8.1, 0.8.2, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 2.0.0, 2.0.1, 2.1.0, 3.0.0, 3.1.0, 3.1.1, 4.0.0, 4.1.0, 4.1.1, 4.2.0, 4.2.1, 4.2.2, 4.2.3, 4.2.4)
ERROR: No matching distribution found for cachetools==5.2.`

Actually I tried many things before raising the issue, such as building paddlepaddle even :) before I wipe and re-install my jetson image I wanted to understand if there is an another way.

btw thanks for the suggestions, I'm new to this world so I'll check them.

**Comment by g-a-pet** [comment]
Which version of paddlepaddle did you try ?

**Comment by mow** [comment]
with the following wheel;
`paddlepaddle_gpu-2.4.2-cp38-cp38-linux_aarch64.whl`

since matplotlib requires python3.8 I stick to this version, couldn't manage to progress even with the versions < 3.8

**Comment by g-a-pet** [comment]
Cp3.8...
Use the cp3.6 
You can find matplotlib earlier versions for python 3.6

**Comment by mow** [comment]
let me try harder with 3.6, will post the results after some more digging with it, thanks.

**Comment by mow** [comment]
:( unfortunately mathplotlib 3.6.2 is a dependency and this depends on min. python 3.8, do you think it's worth to retry with 3.8?

**Comment by g-a-pet** [comment]
I would give up completely and look into tensorrt inference on the jetson nano, then come back and use this repo as inspiration for paddleocr, nms, bytetrack etc. 
Also, you can tweak the code from this repo to work with tensorrt. 
But you first need a working tensorrt engine.
As a comparison, with this repo using pt you might get 2-3 fps with yolov7-tiny. With tensorrt on nano I got 15.
On xavier 50fps.

**Comment by g-a-pet** [comment]
https://github.com/wang-xinyu/tensorrtx

Check out this repo. You also have a nice python example.
