### ISSUE TITLE
Could not build wheels for some required packages on windows 10

### ISSUE THREAD

**Issue by Qmditmore** [theos-ai/easy-yolov7#5]
Failed to build cython-bbox lap lanms-neo Polygon3
ERROR: Could not build wheels for cython-bbox, lap, lanms-neo, Polygon3, which is required to install pyproject.toml-based projects

I received this error and attempted to install the wheels manually and run the pip install that way as well, but it didn't work. I'm stumped here, I really don't know how to obtain these packages.

**Comment by g-a-pet** [comment]
For cython-bbox try first to install cython (pip install cython)
For the rest, share more details individualy and also which architecture (arm, x64), os, python version.
Also try to upgrade pip and setup tools.

**Comment by deadworldisee** [comment]
with python 3.10 pip 23.1 unable to install cython-bbox Error: cl : Command line error D8021 : invalid numeric argument '/Wno-cpp' . installing cython doesnt help. x64 arhitecture.

**Comment by ramacastro** [comment]
Try installing cython-bbox like this:
`pip install -e git+https://github.com/samson-wang/cython_bbox.git#egg=cython-bbox`
