### ISSUE TITLE
Video won't start

### ISSUE THREAD

**Issue by ivankg89** [theos-ai/easy-yolov7#6]
Hello,
When I try to start the video I am getting following output 
[
    {
        "class": "car",
        "confidence": 0.28,
        "x": 234,
        "y": 159,
        "width": 406,
        "height": 300,
        "color": "#00ffc3"
    },
    {
        "class": "motorcycle",
        "confidence": 0.29,
        "x": 233,
        "y": 158,
        "width": 407,
        "height": 302,
        "color": "#00ffc3"
    }
]
W0620 09:55:52.889153  9984 default_variables.cpp:287] Fail to fscanf: Success [0]
W0620 09:55:53.889216  9984 default_variables.cpp:287] Fail to fscanf: Success [0]
W0620 09:55:54.889312  9984 default_variables.cpp:287] Fail to fscanf: Success [0]
W0620 09:55:55.889408  9984 default_variables.cpp:287] Fail to fscanf: Success [0]
W0620 09:55:56.889493  9984 default_variables.cpp:287] Fail to fscanf: Success [0]
W0620 09:55:57.889571  9984 default_variables.cpp:287] Fail to fscanf: Success [0]
W0620 09:55:58.889662  9984 default_variables.cpp:287] Fail to fscanf: Success [0]
W0620 09:55:59.889752  9984 default_variables.cpp:287] Fail to fscanf: Success [0]
W0620 09:56:00.889847  9984 default_variables.cpp:287] Fail to fscanf: Success [0]
W0620 09:56:01.889931  9984 default_variables.cpp:287] Fail to fscanf: Success [0]
W0620 09:56:02.890018  9984 default_variables.cpp:287] Fail to fscanf: Success [0]
W0620 09:56:03.890105  9984 default_variables.cpp:287] Fail to fscanf: Success [0]
W0620 09:56:04.890175  9984 default_variables.cpp:287] Fail to fscanf: Success [0]
W0620 09:56:05.890262  9984 default_variables.cpp:287] Fail to fscanf: Success [0]
W0620 09:56:06.890345  9984 default_variables.cpp:287] Fail to fscanf: Success [0]
W0620 09:56:07.890435  9984 default_variables.cpp:287] Fail to fscanf: Success [0]
W0620 09:56:08.890534  9984 default_variables.cpp:287] Fail to fscanf: Success [0]
W0620 09:56:09.890630  9984 default_variables.cpp:287] Fail to fscanf: Success [0]
W0620 09:56:10.890720  9984 default_variables.cpp:287] Fail to fscanf: Success [0]
W0620 09:56:11.890769  9984 default_variables.cpp:287] Fail to fscanf: Success [0]
W0620 09:56:12.890822  9984 default_variables.cpp:287] Fail to fscanf: Success [0]
W0620 09:56:13.890887  9984 default_variables.cpp:287] Fail to fscanf: Success [0]
W0620 09:56:14.890952  9984 default_variables.cpp:287] Fail to fscanf: Success [0]
W0620 09:56:15.891032  9984 default_variables.cpp:287] Fail to fscanf: Success [0]
W0620 09:56:16.891086  9984 default_variables.cpp:287] Fail to fscanf: Success [0]
W0620 09:56:17.891139  9984 default_variables.cpp:287] Fail to fscanf: Success [0]
W0620 09:56:18.891217  9984 default_variables.cpp:287] Fail to fscanf: Success [0]
W0620 09:56:19.891316  9984 default_variables.cpp:287] Fail to fscanf: Success [0]
W0620 09:56:20.891460  9984 default_variables.cpp:287] Fail to fscanf: Success [0]
W0620 09:56:21.891489  9984 default_variables.cpp:287] Fail to fscanf: Success [0]
W0620 09:56:22.891597  9984 default_variables.cpp:287] Fail to fscanf: Success [0]
W0620 09:56:23.891646  9984 default_variables.cpp:287] Fail to fscanf: Success [0]

The video is not starting to show. Does anyone know what can be a problem?

**Comment by ramacastro** [comment]
try this:
`pip install opencv-python-headless`
